### ISSUE TITLE
about MoViNets

### ISSUE THREAD

**Issue by fangwudi** [Hyperparticle/neural-lemmatizer-allennlp#1]
MoViNets is really an awesome work! May I ask when its code wil be released?

**Comment by Hyperparticle** [comment]
Fortunately for you, it released today! 

https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/movinet

**Comment by fangwudi** [comment]
> Fortunately for you, it released today!
> 
> https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/movinet

great! thanks!
